-- Add display name and SEO metadata fields to Page
ALTER TABLE "Page" ADD COLUMN "name" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Page" ADD COLUMN "metaTitle" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Page" ADD COLUMN "metaDescription" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Page" ADD COLUMN "canonicalUrl" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Page" ADD COLUMN "ogTitle" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Page" ADD COLUMN "ogDescription" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Page" ADD COLUMN "ogImage" TEXT NOT NULL DEFAULT '';
