-- Add display name and SEO fields to Page
ALTER TABLE "Page" ADD COLUMN "name" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Page" ADD COLUMN "seoTitle" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Page" ADD COLUMN "seoDescription" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Page" ADD COLUMN "seoCanonical" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Page" ADD COLUMN "ogTitle" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Page" ADD COLUMN "ogDescription" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Page" ADD COLUMN "ogUrl" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Page" ADD COLUMN "ogImage" TEXT NOT NULL DEFAULT '';
